yarnPath: .yarn/releases/yarn-4.13.0.cjs

nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${NODE_AUTH_TOKEN}"

npmScopes:
  chauhaidang:
    npmRegistryServer: "https://npm.pkg.github.com"
